### ISSUE TITLE
LIstNav not working on Google Chrome

### ISSUE THREAD

**Issue by imranuddinkhattak** [esteinborn/jquery-listnav#23]
Hi,

First of all thank you for your work, i think listnav is a great plugin. I am planning on implementing it on my site, but i noticed that the alphabetical filter links do not work in google chrome. even when viewing the demos on http://ericsteinborn.com/jquery-listnav/ in chrome, the links don't work. If you could tell me how to fix it i would be very greatful. Thanks in advance.
Imran

**Comment by esteinborn** [comment]
@imranuddinkhattak the latest push to the repo should fix this issue for you. #34 worked out that the issue stems from using a touch screen enabled computer and using a mouse. It was only binding to the touch event, and when you click it doesn't fire touch.

Sorry for the confusion about this before.

**Comment by awaischamp** [comment]
I have an issue, the sorting of jQuery-listnav doesn't work when I have selected all items, I am using filterSelector, even when downloaded this example:
http://ericsteinborn.com/jquery-listnav/
and checked out demo-six and added item starting with letter A with class name .last-name
it doesn't showed up at the top, actually its not at all sorting when all items are displayed.
Kindly let me know solution to this.
