### ISSUE TITLE
removeDisabled: true with listnav.min.js hides items for final enabled letter

### ISSUE THREAD

**Issue by stiliyan** [esteinborn/jquery-listnav#24]
Thank you so much for your work on ListNav - the plugin is so easy and quick to setup, and much needed! 

I came across a small bug with the minified version. Specifying the `removeDisabled : true` option when using the minified version in the current release, makes ListNav think there are no entries for the final enabled letter. This works fine in the non-minified version.

Here is a screenshot from Demo #6 when substituting `listnav.js` with `listnav.min.js`:

![screen shot 2015-01-08 at 12 33 58 pm](https://cloud.githubusercontent.com/assets/835142/5667101/1a51b736-9733-11e4-8ade-7553c1d37723.png)

**Comment by esteinborn** [comment]
I fixed this in the latest push. I didnt re-generate the minified code in my build process before my last push, which caused the two files to be out of sync.

Thanks for pointing this out.
