### ISSUE TITLE
How can do it for UTF-8 ?

### ISSUE THREAD

**Issue by yolchunasib** [esteinborn/jquery-listnav#26]
Hello , How can do it for utf-8 alphabet? 
I use it for Azerbaijan language but non-english characters go to other tab

**Comment by esteinborn** [comment]
You could replace the array defined in the plugin with letters from the Azerbaijan alphabet, and it should work just fine.



    _____________________________

**Comment by yolchunasib** [comment]
I do it but not work.

**Comment by yolchunasib** [comment]
non-english characters go to other tab

**Comment by esteinborn** [comment]
Hi, I see what you are saying.

Unfortunately unicode characters are flaky in regexs, which is what The script uses to determine if a letter is valid or "other."

You may have luck using XRegExp and tweaking the line in the code:
if ( **/\W/**.test(firstChar) ) {
  firstChar = '-'; // not A-Z, a-z or 0-9, so considered "other"
  }

Unfortunately I don't have the time to work on this at the moment. I'd love to accept a pull request if you'd like to add the feature though!

**Comment by esteinborn** [comment]
XRegExp w/ Unicode plugin: http://xregexp.com/plugins/#unicode

**Comment by EDsolution** [comment]
Any solution for this jet?

**Comment by esteinborn** [comment]
I provided solutions. But will not be working on it myself.
