### ISSUE TITLE
Not Working With Non-English characters

### ISSUE THREAD

**Issue by vdanelia** [esteinborn/jquery-listnav#27]
Hello Very handy and nice plugin, but I have a trouble, can't make it to work in Georgian and in Russian languages

I changed English "a', 'b', 'c', 'd', 'e', 'f', 'g', 'h" with "a', 'б', 'в', 'г', 'д', 'е', 'ж', 'з" but not working
please update the script.....

With Best wishes

**Comment by esteinborn** [comment]
Please see #26 for reference to utf-8 character sets. Unfortunately the script uses JavaScript regexes and that would require a separate plugin. Willing to accept a PR for this functionality though.
