### ISSUE TITLE
Option for translating the "All" text

### ISSUE THREAD

**Issue by nighto** [esteinborn/jquery-listnav#28]
Include an option for translating the "All" text, just like the ```noMatchText``` option.

**Comment by nighto** [comment]
Oops, I just read the code and noticed that there is an option ```allText```, it's  just not mentioned on the ```README.md``` file. I'll fork and send a pull request.

**Comment by nighto** [comment]
https://github.com/esteinborn/jquery-listnav/pull/29

**Comment by esteinborn** [comment]
Thanks for documenting this!
