### ISSUE TITLE
Add the fact you can place the nav where you want to the documentation

### ISSUE THREAD

**Issue by james1238** [esteinborn/jquery-listnav#30]
It would be useful to mention in the examples/docs, if you place < div id="{myListName}-nav" >< / div > in your markup the plugin puts the Nav inside that element.

**Comment by esteinborn** [comment]
Good idea. Fork it, make the changes, and make a pull request and I'll accept it!

**Comment by james1238** [comment]
Done. Thanks for the plugin!
