### ISSUE TITLE
Possibility of ignoring the prefix i.e (Mr. or Dr.) from a names list

### ISSUE THREAD

**Issue by madmax124** [esteinborn/jquery-listnav#33]
Great plugin, but is there a possibility of ignoring the prefix i.e (Mr. or Dr.) from a names list ?
Could you please help me out ?

**Comment by esteinborn** [comment]
Assuming you closed this because you found the `prefix` option?

**Comment by madmax124** [comment]
Yes, my bad :) Really a perfect plugin, great work!
