### ISSUE TITLE
initLetter not working

### ISSUE THREAD

**Issue by lohiloki** [esteinborn/jquery-listnav#37]
Hi, i implemented your listnav... it does exactly what i wanted. thanks a lot.

But initletter option is not working. First time it loads everything and later it does its filtering thing based on alphabetic click.

Do we have any solution for this. 

here is my site url. : http://phipps.qodesoft.com/where-to-buy/

and its not working either in this too... http://ericsteinborn.com/jquery-listnav/#tabpage_3

Please help me out in this.

**Comment by mattleodunton** [comment]
Hi I have also implemented your listnav. It's working very well and I'm very impressed with it's functionality!

However I am also having an issue with the initletter function. 

It is not working on mobile browsers and returning 'all'

        $(function () {
            $('#demoThree').listnav({
                initLetter: 'a', 
                includeNums: false,
            });
        });

Is there any quick fix for this anyone has discovered? Thanks

**Comment by esteinborn** [comment]
I see that issue as well. looking into it.

**Comment by esteinborn** [comment]
Fixed locally, pushing later in the week. If you change `.trigger(clickEventType)` to `.trigger('click')` it will fix this on your instances @mattleodunton @lohiloki
