### ISSUE TITLE
.bind() no deprecated for .on()

### ISSUE THREAD

**Issue by cosmicnet** [esteinborn/jquery-listnav#38]
Hello,

In jQuery 3 bind() is deprecated and replaced with .on()
You are using bind() on line 279:
$('a', $letters).bind(clickEventType, function (e) {
should now be:
$('a', $letters).on(clickEventType, function (e) {

**Comment by esteinborn** [comment]
Yeah, old code is old.

**Comment by esteinborn** [comment]
Fixed it locally, going to push later this week
