### ISSUE TITLE
Search?

### ISSUE THREAD

**Issue by llahnoraa** [esteinborn/jquery-listnav#39]
Is it possible to include search field (similar to their quick and fast search resutls like this: https://datatables.net)?

**Comment by esteinborn** [comment]
No plans to add that feature. Feel free to add it using data tables separately or include in pull request

On Apr 25, 2017, at 11:19 AM, Aaron Hall <notifications@github.com> wrote:

Is it possible to include search field (similar to their quick and fast search resutls like this: https://datatables.net)?
