### ISSUE TITLE
Option to init as no selection

### ISSUE THREAD

**Issue by mattwillms** [esteinborn/jquery-listnav#40]
Can we have an option for no letter to be selected on init?

Instead you could have nothing displayed or a message you could set? 

Possibly: blankInitText , etc...

Thanks!

**Comment by esteinborn** [comment]
Could be possible, would need to add a new option and check it after this line:
https://github.com/esteinborn/jquery-listnav/blob/master/jquery-listnav.js#L115

Feel free to add it in and submit a PR.

**Comment by esteinborn** [comment]
Actually, I just worked on this, it was pretty easy. I'm going to update it later this week.
