### ISSUE TITLE
Add package to NPM registry

### ISSUE THREAD

**Issue by mauricios** [esteinborn/jquery-listnav#41]
Since Bower is no longer supported, It will be nice to have the package in the NPM registry

**Comment by mauricios** [comment]
@esteinborn I've temporarily added to NPM registry under my account. Please let me know if you want to be the holder of this package on NPM and I'll deleted it from my account.

**Comment by esteinborn** [comment]
Thats fine. It's minimally maintained anyway.

thanks.
