### ISSUE TITLE
Question about counter

### ISSUE THREAD

**Issue by NiekRood** [esteinborn/jquery-listnav#42]
Is it possible to have the counter below in a span instead off above the letters?
It now only shows on hovering but it would be nice to have it somewhere below the listnav.

Something like this:

**A** B C D E F
------------------------------------Letter A has **4** results
A
AA
AAA
AAAA

**Comment by esteinborn** [comment]
Currently there is an entire function devoted to the hover state, which changes the contents of a single element to the count of the hovered item.

I'd be willing to accept a PR for this feature, but don't have the time to do it myself.
