### ISSUE TITLE
Last Alphabet (Z) count always shows 0

### ISSUE THREAD

**Issue by ronit87** [esteinborn/jquery-listnav#43]
Count always shows 0 even if there are more than 1 items in last Alphabet(Z) in List and having following javascript code.

```
jQuery('#vatlist').listnav({
      includeNums: false,
      includeOther: true,
      allText: 'ALL Countries'
});
```

**Comment by esteinborn** [comment]
What jQuery version are you running?

**Comment by esteinborn** [comment]
I cannot reproduce.
