### ISSUE TITLE
Multiple lists - how to pass to other lists, the selection on the first list

### ISSUE THREAD

**Issue by moplin** [esteinborn/jquery-listnav#44]
Pls I have two small questions.
I have a big page with four lists, I am usong mdl-grid and mdl-card to build the content.
1. Is tehre a way to make all lists react to a user clicking on any letter so all lists will filter at the same time?
2. I ended using an id for each list, I cant find a way to make them work with a class, I am missing something? Or you think mdl braking something?
Thanks
![16112017002](https://user-images.githubusercontent.com/9134990/32900599-d6b02a20-cabb-11e7-8265-ab7881276c50.png)
![16112017003](https://user-images.githubusercontent.com/9134990/32900834-6207dfe6-cabc-11e7-8f05-4fbf93a8829f.png)

**Comment by esteinborn** [comment]
No, that would require changing the main function of the application. 

if you are looking to hack it up, take a look at the `this.each(function()` which creates teh separation between each of the lists.
